namespace ZamboniCommonComponents.Structs;

public enum DynamicMessageType : int
{
    DYNAMICMESSAGE_TYPE_MARKETPLACE = 0,
    DYNAMICMESSAGE_TYPE_WEBOFFER = 1,
    DYNAMICMESSAGE_TYPE_SCREEN = 2,
    DYNAMICMESSAGE_TYPE_FEATURE = 3,
    DYNAMICMESSAGE_TYPE_NONE = 4,
    DYNAMICMESSAGE_TYPE_SURVEY = 5,
    DYNAMICMESSAGE_TYPE_ONDEMAND = 6,
    DYNAMICMESSAGE_TYPE_CLUBS = 7,
    DYNAMICMESSAGE_TYPE_MATCHMAKING = 8,
    DYNAMICMESSAGE_TYPE_SPONSOREDEVENT = 9,
    DYNAMICMESSAGE_TYPE_OTP = 10,
    DYNAMICMESSAGE_TYPE_LEAGUES = 11
}