namespace ZamboniUltimateTeam.Structs;

public enum AiGroup : int
{
    CARDHOUSE_AIGROUP_ALL = 0,
    CARDHOUSE_AIGROUP_UPTO1STAR = 1,
    CARDHOUSE_AIGROUP_UPTO2STAR = 2,
    CARDHOUSE_AIGROUP_UPTO3STAR = 3,
    CARDHOUSE_AIGROUP_UPTO4STAR = 4,
    CARDHOUSE_AIGROUP_UPTO5STAR = 5,
    CARDHOUSE_AIGROUP_INTERNATIONAL = 6,
    CARDHOUSE_AIGROUP_MAX = 7,
}