namespace ZamboniUltimateTeam.Structs;
    
public enum CardSubTypeSearchParameter : int
{
    SEARCH_TEAM_INFORMATION_LOGOS = 12,
    SEARCH_TEAM_INFORMATION_JERSEYS = 13,
    SEARCH_TRAINING_PLAYER = 15,
    SEARCH_TRAINING_GOALIE = 16,
    SEARCH_TRAINING_POSITION = 17,
    SEARCH_HEALING_ANY_INJURY = 26,
    SEARCH_HEALING_TORSO = 23,
    SEARCH_HEALING_ARMS = 24,
    SEARCH_HEALING_LEGS = 25,
}