namespace ZamboniUltimateTeam.Structs;

public enum MatchResult : byte
{
    CARDHOUSE_MATCHRESULT_INVALID = 0,
    CARDHOUSE_MATCHRESULT_WON = 1,
    CARDHOUSE_MATCHRESULT_LOST = 2,
    CARDHOUSE_MATCHRESULT_WON_CUP = 3,
    CARDHOUSE_MATCHRESULT_DRAW = 4,
    CARDHOUSE_MATCHRESULT_LOST_CUP = 5,
}