namespace ZamboniUltimateTeam.Structs;

public enum PlayGameState : int
{
    CARDHOUSE_PGSTATE_INVALID = 0,
    CARDHOUSE_PGSTATE_STARTING = 1,
    CARDHOUSE_PGSTATE_ENDING = 2,
    CARDHOUSE_PGSTATE_MIDDLE = 3,
    CARDHOUSE_PGSTATE_DEBUG = 4,
}