namespace ZamboniUltimateTeam.Structs;

public enum ResultContext : byte
{
    CARDHOUSE_STICKERBOOK_STAT_RESULT_CONTEXT_INVALID = 0,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_CONTEXT_YEAR = 1,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_CONTEXT_COUNTRY = 2,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_CONTEXT_LEAGUE = 3,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_CONTEXT_TEAM = 4,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_CONTEXT_STADIUMS = 5,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_CONTEXT_BALLS = 6,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_CONTEXT_MANAGERS = 7,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_CONTEXT_STAFF = 8,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_CONTEXT_MAX = 9,
}