namespace ZamboniUltimateTeam.Structs;

public enum ResultType : byte
{
    //TODO Not all confirmed
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_INVALID = 0,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_PLAYERS = 1,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_PLAYERS_BRONZE = 2,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_STAFF_HEADCOACH = 10,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_BALLS = 12,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_STADIA = 20,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_KITS = 40,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_KITS_HOME = 41,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_KITS_AWAY = 42,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_BADGES = 45,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_BADGEDBID = 17,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_LEAGUELOGOS = 18,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_LEAGUELOGODBID = 19,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_TROPHIES = 50,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_TROPHIES_OFFLINE = 51,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_TROPHIES_ONLINE = 52,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_TROPHIES_LIVE = 53,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_TROPHIES_PLAYOFF = 54,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_CONSUMABLES = 60,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_CONSUMABLES_CONTRACT = 61,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_CONSUMABLES_TRAINING = 62,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_CONSUMABLES_TEAMTALKS = 63,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_CONSUMABLES_FITNESS = 64,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_CONSUMABLES_HEALING = 65,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_STARS_OF_THE_WEEK = 70,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_LEGENDS = 71,
    CARDHOUSE_STICKERBOOK_STAT_RESULT_TYPE_MAX = 255,
}