namespace ZamboniUltimateTeam.Structs;

public enum RewardFlag : int
{
    //Id's not confirmed
    CARDHOUSE_REWARD_FLAG_NONE = 0,
    CARDHOUSE_REWARD_FLAG_ONLINE_PASS = 1,
    CARDHOUSE_REWARD_FLAG_WELCOME = 2,
    CARDHOUSE_REWARD_FLAG_DEMO_PLAY = 3,
    CARDHOUSE_REWARD_FLAG_DEMO_TOURNY_WON = 4,
    CARDHOUSE_REWARD_FLAG_DEMO_FRIEND_INVITED = 5,
    CARDHOUSE_REWARD_FLAG_WEB_1 = 6,
    CARDHOUSE_REWARD_FLAG_WEB_2 = 7,
    CARDHOUSE_REWARD_FLAG_WEB_3 = 8,
    CARDHOUSE_REWARD_FLAG_WEB_4 = 9,
    CARDHOUSE_REWARD_FLAG_WEB_5 = 10,
    CARDHOUSE_REWARD_FLAG_PERSISTENCE = 1024,
    CARDHOUSE_REWARD_FLAG_COLLECTION = 11,
    
}