namespace ZamboniUltimateTeam.Structs;

public enum TournamentType : byte
{
    CARDHOUSE_TOURNAMENTTYPE_OFFLINE = 0,
    CARDHOUSE_TOURNAMENTTYPE_ONLINE = 1,
    CARDHOUSE_TOURNAMENTTYPE_LIVE_OFFLINE = 2,
    CARDHOUSE_TOURNAMENTTYPE_LIVE_ONLINE = 3,
    CARDHOUSE_TOURNAMENTTYPE_PLAYOFF = 4,
    CARDHOUSE_TOURNAMENTTYPE_MAX = 5,
}